version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: programacao-web-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # standard AMQP protocol port
      - "15672:15672" # management UI port
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"

  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    ports:
      - "9042:9042" # Cassandra CQL port
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-db

volumes:
  postgres_data:
  rabbitmq_data:
  cassandra_data:
