name: Docker Pytest Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Execute tests
        run: docker run --name my-app my-python-app pytest /tests
